# Generated by Django 5.0.7 on 2024-08-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Pessoal', 'Pessoal'), ('Trabalho', 'Trabalho'), ('Outro', 'Outro')], default='Outro', max_length=50),
        ),
    ]
