# Generated by Django 5.0.7 on 2024-08-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], default='Média', max_length=50),
        ),
    ]
